name: Sync della repo sullo Space HF
env:
HF_USERNAME: maxilibre71
HF_SPACE: maxilibre71space
on:
schedule:
- cron: "0 3 * * *"
workflow_dispatch:
jobs:
sync:
runs-on: ubuntu-latest
steps:
- name: Request Factory Rebuild
run: 
|curl -X POST \
-H "Authorization: Bearer ${{ secrets.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}}" \
"https://huggingface.co/api/spaces/maxilibre71/maxilibre71space/restart?factory=true”
